- name: all tasks run as virt_user
  become: yes
  become_user: "{{ virt_user }}"
  tags:
    - domains
    - lab
  block:
    - name: define undecloud node
      when: item.name is match('^undercloud')
      virt:
        name: "{{ vm_prefix }}-{{ item.name }}"
        command: define
        xml: "{{ lookup('template', 'undercloud.xml.j2') }}"
        uri: "qemu:///system"
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: define overcloud node
      when:
        - item.0.name is not match('^undercloud')
      virt:
        name: "{{ vm_prefix }}-oc{{ item.1 }}-{{ item.0.name }}"
        command: define
        xml: "{{ lookup('template', 'domain.xml.j2') }}"
        uri: "qemu:///system"
      loop: "{{ vms|product(overclouds_range)|list }}"
      loop_control:
        label: "oc{{ item.1 }}-{{ item.0.name }}"

    - name: fetch all MAC addresses
      when: item.0.name is not match('^undercloud')
      shell: |
        virsh -c 'qemu:///system' domiflist {{ vm_prefix }}-oc{{ item.1 }}-{{ item.0.name }} | awk 'NR==3 {print $5}'
      register: oc_mac_addresses
      loop:  "{{ vms|product(overclouds_range)|list }}"
      loop_control:
        label: "oc{{ item.1 }}-{{ item.0.name }}"

    - name: start undercloud
      tags:
        - start-domains
      virt:
        name: "{{ vm_prefix }}-{{ item.name }}"
        state: running
        uri: "qemu:///system"
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.name is match('^undercloud')

    - name: fetch associated IP address for running domains
      tags:
        - start-domains
        - gen-ssh-config
        - inventory
      shell: |
        virsh --connect qemu:///system domifaddr "{{ vm_prefix }}-{{ item.name }}" | \
        awk '/ipv4/ {print $4}' | head -n1
      register: ip_address
      retries: 10
      delay: 5
      until:
        - ip_address.stdout != ""
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.name is match('^undercloud')

    - name: ensure variable ip_address is not empty
      tags:
        - start-domains
        - gen-ssh-config
      fail:
        msg: "No IP address for undercloud"
      when:
        - ip_address.results[0].stdout == ""

    - name: populate ssh_config
      tags:
        - start-domains
        - gen-ssh-config
      template:
        dest: "{{ basedir }}/.ssh/config"
        src: ssh_config.j2
        group: "{{ virt_user }}"
        mode: 0644
        owner: "{{ virt_user }}"

- name: provision hosts file
  tags:
    - domains
    - start-domains
    - lab
  lineinfile:
    line: "{{ item.stdout|replace('/24','') }} {{ item.item.name }} {{ vm_prefix }}-{{ item.item.name }}"
    path: /etc/hosts
    regexp: "{{ item.item.name }}$"
    state: present
  loop: "{{ ip_address.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.stdout is defined

- name: inject domains in inventory
  tags:
    - domains
    - start-domains
    - inventory
    - lab
  add_host:
    hostname: "{{ item.item.name }}"
    ansible_host: "{{ item.stdout|replace('/24','') }}"
    ansible_python_interpreter: "{{ python_interpreter }}"
  loop: "{{ ip_address.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.stdout is defined

- name: inject config on ansible host
  tags:
    - domains
    - start-domains
    - inventory
    - gen-ssh-config
    - lab
  local_action:
    module: blockinfile
    path: ~/.ssh/config
    marker: "## {mark} {{ item.item.name }}"
    create: yes
    mode: 0600
    block: |
      Host {{ item.item.name }} {{ item.stdout|replace('/24','') }}
        #ProxyCommand ssh -o 'ForwardAgent yes' {{ virt_user }}@{{ ansible_host }} 'ssh-add && nc {{ item.stdout|replace('/24','') }} %p'
        ProxyJump {{ virt_user }}@{{ ansible_host }}
        Hostname {{ item.stdout|replace('/24','') }}
        User root
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
  loop: "{{ ip_address.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.stdout is defined

- name: wait for undercloud to be up
  tags:
    - domains
    - start-domains
    - inventory
    - gen-ssh-config
    - lab
  wait_for_connection:
    timeout: 300
    delay: 30
    sleep: 3
