- name: common tags
  tags:
    - vbmc
    - lab
    - builder-bootstrap
  block:
    - name: push virtualbmc script
      file:
        path: /usr/local/sbin/vbmc-run
        state: absent

    - name: deactivate custom vbmc service
      service:
        name: vbmc
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: remove custom systemd unit file
      file:
        path: /etc/systemd/system/vbmc.service
        state: absent

    - name: start virtualbmc
      service:
        name: virtualbmc
        enabled: yes
        state: started

    - name: get all defined VMs
      virt:
        command: list_vms
      register: list_vms

    - name: Create the Virtual BMCs
      when: item.0.name is not match('^undercloud')
      command: "vbmc add {{vm_prefix}}-oc{{ item.1 }}-{{ item.0.name }} --port 10{{'%02d'|format(item.1)}}{{ vm_idx }} --libvirt-uri qemu:///system --username ADMIN --password ADMIN"
      args:
        creates: "/root/.vbmc/{{vm_prefix}}-oc{{ item.1 }}-{{ item.0.name }}/config"
      loop: "{{ vms|product(overclouds_range)|list }}"
      loop_control:
        label: "oc{{ item.1 }}-{{ item.0.name }}"
        index_var: vm_idx
      register: vbmc
      ignore_errors: yes

    - name: Start the Virtual BMCs (virtualbmc >= 1.4.0+)
      command: "vbmc start {{vm_prefix}}-oc{{ item.1 }}-{{ item.0.name }}"
      loop: "{{ vms|product(overclouds_range)|list }}"
      loop_control:
        label: "oc{{ item.1 }}-{{ item.0.name }}"
      ignore_errors: yes
      when:
        - vbmc.changed
        - item.0.name is not match('^undercloud')

    - name: open firewall on libvirt link
      iptables:
        action: insert
        chain: INPUT
        comment: "allow vbmc access from undercloud"
        destination: "192.168.122.1"
        jump: ACCEPT
        protocol: udp
