- name: copy undercloud.conf sample
  copy:
    dest: /home/stack/undercloud.conf
    src: "{{ undercloud_sample }}"
    remote_src: yes
    owner: stack
    group: stack
    mode: 0640

- name: Enable masquerading in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: ctlplane-subnet
    option: masquerade
    value: true
    mode: 0640
    backup: no

- name: Enable undercloud hieradata for low memory
  ini_file:
    path: /home/stack/undercloud.conf
    section: DEFAULT
    option: hieradata_override
    value: /home/stack/hieradata_undercloud_low_memory.yaml
    mode: 0640
    backup: no
  when: undercloud_low_memory|bool

- name: Create hieradata_undercloud_low_memory.yaml
  template:
    dest: /home/stack/hieradata_undercloud_low_memory.yaml
    src: hieradata_undercloud_low_memory.yaml.j2
  when: undercloud_low_memory|bool

- name: custom configuration in undercloud.conf
  ini_file:
    path: /home/stack/undercloud.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0640
    backup: no
  loop: "{{ undercloud_config }}"
  loop_control:
    label: "{{ item.option }}"

- name: run commands as stack user
  become: yes
  become_user: stack
  block:
    - name: generate baremetal.json file
      tags:
        - baremetal
      template:
        dest: /home/stack/baremetal.json
        mode: '0644'
        src: baremetal.json.j2

    - name: create per overcloud yml directory
      tags:
        - baremetal
      file:
        path: "/home/stack/overcloud-{{ item }}-yml"
        state: directory
      loop: "{{ range(0, overclouds)|list }}"

    - name: push common overcloud settings
      tags:
        - baremetal
      copy:
        dest: "/home/stack/"
        src: "{{ item }}"
      with_fileglob: 'files/overcloud/*.yaml'

    - name: push node placement
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/placement.yaml"
        src: node-placement.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push scale setting
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/scale.yaml"
        src: scale.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push per-overcloud network data
      tags:
        - baremetal
      template:
        dest: "/home/stack/oc{{ item }}-network-data.yaml"
        src: oc-network-data.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push per-overcloud network env
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/network-env.yaml"
        src: oc-network-env.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push ceph settings
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/ceph-params.yaml"
        src: ceph-params.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"
      when:
        - vms|map(attribute='name')|select("match", '^ceph')|list|length > 0

    - name: push container-cli setting
      tags:
        - baremetal
      template:
        dest: "/home/stack/overcloud-{{ item }}-yml/container-cli.yaml"
        src: container-cli.yaml.j2
      loop: "{{ range(0, overclouds)|list }}"

    - name: push local_images.yaml setting
      tags:
        - baremetal
      template:
        dest: /home/stack/local_images.yaml
        src: local_images.yaml

    - name: push basic deploy script
      tags:
        - baremetal
      template:
        dest: "/home/stack/deploy-overcloud-{{ item }}.sh"
        src: overcloud-deploy.sh.j2
        mode: 0750
      loop: "{{ range(0, overclouds)|list }}"

    - name: push config-download script
      tags:
        - baremetal
      template:
        dest: "/home/stack/config-download-oc{{ item }}.sh"
        src: overcloud-configdl.sh.j2
        mode: 0750
      loop: "{{ range(0, overclouds)|list }}"

    - name: create image directory
      tags:
        - baremetal
        - overcloud-images
      file:
        path: "/home/stack/overcloud_imgs"
        state: directory
